import { Pool } from 'pg'
import fs from 'node:fs/promises'
import path from 'node:path'
let pool
function db() { if (!pool) { if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL must be configured for the vendor catalog.'); pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined }) } return pool }
const normalize = (v) => String(v ?? '').trim().toUpperCase().replace(/\s+/g, ' ')
export async function initCatalog() { await db().query(await fs.readFile(path.resolve('server/db/schema.sql'), 'utf8')) }
export async function listCatalog() { const { rows } = await db().query(`SELECT p.*,COALESCE(json_agg(DISTINCT a.alias) FILTER(WHERE a.id IS NOT NULL),'[]') aliases,COALESCE(json_agg(DISTINCT jsonb_build_object('id',v.id,'vendorName',v.vendor_name,'vendorPartNumber',v.vendor_part_number,'purchaseUrl',v.purchase_url,'latestPrice',v.latest_price,'currency',v.currency,'availability',v.availability,'isDefault',v.is_default,'active',v.active)) FILTER(WHERE v.id IS NOT NULL),'[]') listings FROM catalog_parts p LEFT JOIN part_aliases a ON a.catalog_part_id=p.id LEFT JOIN vendor_listings v ON v.catalog_part_id=p.id GROUP BY p.id ORDER BY p.canonical_part_number`); return rows }
export async function upsertCatalogPart(input) { const client = await db().connect(); try { await client.query('BEGIN'); const pn=normalize(input.canonicalPartNumber); if(!pn) throw new Error('Onshape Part Number is required.'); const part=(await client.query(`INSERT INTO catalog_parts(canonical_part_number,description,vendor_agnostic,vendor_unknown) VALUES($1,$2,$3,$4) ON CONFLICT(canonical_part_number) DO UPDATE SET description=COALESCE(EXCLUDED.description,catalog_parts.description),vendor_agnostic=EXCLUDED.vendor_agnostic,vendor_unknown=EXCLUDED.vendor_unknown,updated_at=now() RETURNING *`,[pn,input.description||null,!!input.vendorAgnostic,!!input.vendorUnknown])).rows[0]; for(const alias of input.aliases||[]){const a=normalize(alias);if(a)await client.query('INSERT INTO part_aliases(catalog_part_id,alias) VALUES($1,$2) ON CONFLICT DO NOTHING',[part.id,a])} for(const x of input.listings||[]){if(!x.vendorName||!x.vendorPartNumber)continue;await client.query(`INSERT INTO vendor_listings(catalog_part_id,vendor_name,vendor_part_number,purchase_url,latest_price,currency,availability,is_default,active) VALUES($1,$2,$3,$4,$5,COALESCE(NULLIF($6,''),'USD'),$7,$8,$9) ON CONFLICT(catalog_part_id,vendor_name,vendor_part_number) DO UPDATE SET purchase_url=EXCLUDED.purchase_url,latest_price=EXCLUDED.latest_price,currency=EXCLUDED.currency,availability=EXCLUDED.availability,is_default=EXCLUDED.is_default,active=EXCLUDED.active,updated_at=now()`,[part.id,x.vendorName,x.vendorPartNumber,x.purchaseUrl||null,x.latestPrice||null,x.currency||'USD',x.availability||null,!!x.isDefault,x.active!==false]);if(x.isDefault)await client.query('UPDATE vendor_listings SET is_default=false WHERE catalog_part_id=$1 AND id<>(SELECT id FROM vendor_listings WHERE catalog_part_id=$1 AND vendor_name=$2 AND vendor_part_number=$3)',[part.id,x.vendorName,x.vendorPartNumber])} await client.query('COMMIT');return part }catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
export async function findListing(partNumber) { const v=normalize(partNumber);if(!v)return null;const {rows}=await db().query(`SELECT v.id,v.vendor_name AS "vendorName",v.vendor_part_number AS "vendorPartNumber",v.purchase_url AS "purchaseUrl",v.latest_price AS "latestPrice",v.currency,v.availability,v.active,p.canonical_part_number AS "canonicalPartNumber" FROM vendor_listings v JOIN catalog_parts p ON p.id=v.catalog_part_id LEFT JOIN part_aliases a ON a.catalog_part_id=p.id WHERE v.active AND (p.canonical_part_number=$1 OR a.alias=$1) ORDER BY v.is_default DESC,v.id LIMIT 1`,[v]);return rows[0]||null }
export async function findListings(partNumber) { const v=normalize(partNumber);if(!v)return [];const {rows}=await db().query(`SELECT v.id,v.vendor_name AS "vendorName",v.vendor_part_number AS "vendorPartNumber",v.purchase_url AS "purchaseUrl",v.latest_price AS "latestPrice",v.currency,v.availability,v.active,v.is_default AS "isDefault",p.canonical_part_number AS "canonicalPartNumber" FROM vendor_listings v JOIN catalog_parts p ON p.id=v.catalog_part_id LEFT JOIN part_aliases a ON a.catalog_part_id=p.id WHERE v.active AND (p.canonical_part_number=$1 OR a.alias=$1) ORDER BY v.is_default DESC,v.id`,[v]);return rows }
